### PR TITLE
[FEAT] Added option to add grid to resulting xls-table

### PR DESCRIPTION
**Pull request by BafDyce**
This allows adding a grid with customizable gaps for both, the vertical and the
horizontal axis. By default no grid is added.

Usage: --grid <vertical gap> <horizontal gap>
Specifies the number of pixels between the grid lines, per axis.
Zero or negative numbers won't produce any grid lines.
Command line options are checked whether they specify a valid int.

Tested on Linux Mint 17.1 (64-bit) and LibreOffice 4.2.8.2

### CODE REVIEW

**Comment by BafDyce** [comment]
First PR ever :) :P

I tried to adept your coding styles (max 80 lines, 4 spaces instead of tabs, etc.). If you want anything changed, please tell me.
I also know that it looks a bit ugly how I check the command line arguments. Any ideas on how I could do that better? I haven't really programmed in Python yet, this was the first "real programming" in this language.

Also: Would you want me to also update the readme and attach an image showing the grid?
If so, should I amend it to this commit or in a new one?

**Comment by Dobiasd** [comment]
You idea for an optional grid sounds nice. I wanted to try out your code with [this image](http://i.imgur.com/cK7LutB.png) before merging your pull request to see the output. But even without the new grid option the following call

```
python3 img2xls.py libre images/lenna_64x64.png
```

results in the following error on my machine:

```
Traceback (most recent call last):
  File "img2xls.py", line 181, in <module>
    sys.exit(main())
  File "img2xls.py", line 178, in main
    img2xls(size_dict[switch], img_path, xls_path, grid_gap_vert,grid_gap_horiz)
  File "img2xls.py", line 119, in img2xls
    set_cell_colors(pal_img, style_lookup, sheet1, grid_gap_vert,grid_gap_horiz)
  File "img2xls.py", line 107, in set_cell_colors
    map2d(pal_img.size, write_sheet_cell)
  File "img2xls.py", line 28, in map2d
    func(x_pos, y_pos)
  File "img2xls.py", line 105, in write_sheet_cell
    sheet.write(y_pos, x_pos, ' ', style)
  File "/usr/local/lib/python2.7/dist-packages/xlwt/Worksheet.py", line 1088, in write
    self.row(r).write(c, label, style)
  File "/usr/local/lib/python2.7/dist-packages/xlwt/Row.py", line 237, in write
    style_index = self.__parent_wb.add_style(style)
  File "/usr/local/lib/python2.7/dist-packages/xlwt/Workbook.py", line 324, in add_style
    return self.__styles.add(style)
  File "/usr/local/lib/python2.7/dist-packages/xlwt/Style.py", line 92, in add
    return self._add_style(style)[1]
  File "/usr/local/lib/python2.7/dist-packages/xlwt/Style.py", line 151, in _add_style
    raise ValueError("More than 4094 XFs (styles)")
ValueError: More than 4094 XFs (styles)
```

Can you confirm this behavior in your environment? If so it would be great if you could fix it. A remark in the README in the same commit would also be good. After we have everything working, we can do possibly needed style adjustments in a next iteration.

Btw: I intially used [PyLint](http://www.pylint.org/) with its default configuration to check the style of the code in this repo.

**Comment by BafDyce** [comment]
Yes, I can confirm this behaviour!
I will look into it and see whether I can fix it.

Also, I'll add the changes to the readme too.

**Comment by BafDyce** [comment]
So, I pushed two more commits. The first one fixes the bug, the second one updates the readme.
I don't know how to correctly squash them together into one single commit, without rewriting history (by using rebase).

The bug was caused due to the limitation of a maximum of 4094 XFs styles. My first approach apparently added a new style for every cell. This behaviour is now changed: All different _possible_ style-variations (cell without border, cell with top border, cell with left border, cell with both, top and left border) are now pre-generated and afterwards re-used.

I hope the way I did this (adding the styles to style_lookup[], with an appropriate offset; defined with global constants) is OK for you.

**Comment by Dobiasd** [comment]
Looks good. Thanks for writing this extension. I only did some adjustments according to PyLint subsequently to the code.

**Comment by Dobiasd** [comment]
Also did a bit of refactoring to avoid some code repetition. The command line argument parsing still could be improved, I guess. Do you want to give it a try using [argparse](https://docs.python.org/3/howto/argparse.html)? :-)

**Comment by BafDyce** [comment]
You're welcome! Glad that I could help improving this neat tool :)

I can try to use argparse, however I don't know how much time I have in the next few days.

**Pull request merged**
